[package]
name = "simplerdb"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"

[dependencies]
chrono = "0.4.38"
expect-test = "1.5.0"
pretty-hex = "0.4.1"
